//
// Created by jrstringfellow on 3/24/19.
//

#ifndef CS201_PORTFOLIO_INTERFACECONTROLLER_H
#define CS201_PORTFOLIO_INTERFACECONTROLLER_H
void runLogging(char*);
#endif //CS201_PORTFOLIO_INTERFACECONTROLLER_H
